### ISSUE TITLE
Issue with delete functionality in Django admin inline formset

### ISSUE THREAD

**Issue by WajahatKanju** [app-generator/django-admin-datta#2]
**Description**:

Steps to Reproduce:

1.     Start a Django project.
2.     Include the admin_datta.apps.AdminDattaConfig app in the INSTALLED_APPS setting.
3.     Configure the necessary models and inline formsets in the Django admin.
4.     Access the Django admin and navigate to a page where the inline formsets are displayed.
5.     Attempt to delete an inline formset entry.

_Expected Behavior:_
The inline formset entry should be successfully deleted without any errors.

Actual Behavior:
The delete functionality in the Django admin inline formset is not working as expected. Clicking on the delete button does not trigger the deletion of the corresponding entry, and no error messages are displayed.

Additional Information:

-     When the admin_datta app is disabled in the INSTALLED_APPS setting, the delete functionality works fine.
-     Django version: [Insert Django version]
-     Relevant code snippets:
-         INSTALLED_APPS configuration:

`INSTALLED_APPS = [
    "admin_datta.apps.AdminDattaConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "compressor",
    "sass_processor",
    "students.apps.StudentsConfig",
    "academics.apps.AcademicsConfig",
]`

-     Inline formset configuration in the Django admin.

Any error messages or warnings observed in the browser console or Django server logs.
Any relevant changes or updates made to the code or configuration related to the Django admin or inline formsets.
Steps taken to troubleshoot the issue (if any).
Stack Overflow Question:
To provide more context and engage with the community, I have also posted a related question on Stack Overflow: [Stack Overflow Question](https://stackoverflow.com/questions/76367281/issue-with-delete-functionality-in-django-admin-inline-formset)

Note:
Feel free to provide additional information or clarify any specific details that may help in resolving this issue.

**Comment by app-generator** [comment]
Hello @WajahatKanju 

Thank you for using our products. 
Someone from the team will assist. 

@mominur-helios please take a look.
Ty!

**Comment by ghost** [comment]
Hello @WajahatKanju ,
The issue has been resolved in the last commit, you could pull the latest changes.

**Comment by app-generator** [comment]
Hello @WajahatKanju 

Issue fixed in release `v1.0.8`. Please update. 

TY @mominur-helios for the fix.

**Comment by WajahatKanju** [comment]
Issue Still Persists. 
Project setup: Start by creating a new project for debugging purposes. You can use the following command:

`django-admin startproject debug_project`

Download the latest version (v1.0.8): Navigate into the project directory and clone the "django-admin-datta" repository with the specific version using Git:

cd debug_project
App and module creation: Create a new app within the project by running the following command:

`python manage.py startapp debug_app`

Model creation: Open the models.py file within the debug_app directory and define a model called "Topic" with a foreign key to the "Module" model. Here's an example:
```

from django.db import models

class Module(models.Model):
    # Module model fields here

class Topic(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    # Topic model fields here

```

Tabular admin configuration: Open the admin.py file within the debug_app directory and register the "Topic" model as a tabular inline with the "Module" admin. Here's an example:
```

from django.contrib import admin
from .models import Module, Topic

class TopicInline(admin.TabularInline):
    model = Topic

class ModuleAdmin(admin.ModelAdmin):
    inlines = [TopicInline]

admin.site.register(Module, ModuleAdmin)
```

Create a superuser: Run the following command to create a new superuser:

`python manage.py createsuperuser`

Follow the prompts to set the username, email, and password for the superuser.

Test the issue: Start the development server using the following command:

`python manage.py runserver`

Open your web browser and navigate to http://localhost:8000/admin/. Log in with the superuser credentials you created.

    Locate the "Module" section and click on it to access the admin page for modules.
    Create a new module.
    In the module's detail page, verify if the "Topic" tabular inline section is present.
    Check if the delete button is visible for the inline topics. If the button is not found, it indicates that the issue is occurring.
![Screenshot 2023-05-31 142320](https://github.com/app-generator/django-admin-datta/assets/48358590/48b88254-6198-4a59-abbd-8bcb90426691)

Additionally, I noticed another issue related to the detection of Django when using the "django-admin-datta" app. The default prepopulate__init.js file seems to be unable to detect Django in this setup. When inspecting the code, I encountered the following error:
`Uncaught ReferenceError: django is not defined`

Disable The app also fixes this issue

**Comment by ghost** [comment]
It is working fine. Check out this link
https://github.com/app-generator/django-admin-datta/assets/101915710/75cb31c4-5269-4249-9c2e-e8d6036fe9f0

### models.py
```
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=255)

class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
```
### admin.py
```
from django.contrib import admin
from .models import Author, Book

class BookInline(admin.TabularInline):
    model = Book
    extra = 1

class AuthorAdmin(admin.ModelAdmin):
    inlines = [BookInline]

admin.site.register(Author, AuthorAdmin)
```

**Comment by WajahatKanju** [comment]
Can you provide me with the full code. maybe i have done something wrong.
cuz it is till not showing up in my app. even though i have the latest
version 1.0.8
See the video

**Comment by WajahatKanju** [comment]
Sorry it does work. but can you point out where the issue is. i have my own
templates which override yours one when i delete my templates directory
then it works as intend. can you tell me where the issue is so i can fix i
in my own implementation?

**Comment by ghost** [comment]
If you have ```base.html``` in your own templates then you might miss these line below,
```
<!DOCTYPE html>
{% load i18n static admin_datta %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% get_direction as direction %}
{% get_admin_setting as admin_setting %}
<html lang="en">
<head>
  {% include 'includes/head.html' %}
  {% block extrastyle %}{% endblock extrastyle %}
  {% block extrahead %}{% endblock extrahead %}
</head>
```

**Comment by WajahatKanju** [comment]
Issue with Django Admin Auto-Select Behavior

Dear app-generator/django-admin-datta Developers,

I hope this email finds you well. I am writing to bring to your attention
another issue #3. I am currently facing with your third-party app in my
Django admin.

The problem arises when I attempt to create a new object in the admin
interface that has a foreign key relationship with another object.
Normally, after creating the related object by clicking the "+" icon below
the input field, the newly created object appears immediately and is
auto-selected. However, in the current situation, I have to manually
refresh the page for the new object to be displayed and selected
automatically.

I have tried some basic troubleshooting steps on my end, such as clearing
browser cache and checking for JavaScript errors in the developer console.
Unfortunately, these measures have not resolved the issue. Additionally, I
have verified that I am using the latest compatible versions of Django and
your third-party app.

Before reaching out to you, I wanted to ensure that I had exhausted all
possible solutions. I have reviewed any customizations or overrides I made
related to this functionality, but have not identified any potential
conflicts.

I kindly request your assistance in resolving this matter. If you have any
insights, suggestions, or updates related to the auto-select behavior in
Django admin, I would greatly appreciate your guidance. If there are any
known issues or recent updates regarding this specific functionality,
please let me know.

I value the functionality and reliability your third-party app provides,
and I believe that working together, we can address this issue and ensure a
smooth user experience for all Django admin users.

Thank you for your attention to this matter. I look forward to your prompt
response and resolution.

Best regards,
Wajahat Ahmad
